<?php
/**
 * blog
 * ============================================================================
 * 版权所有 2015-2017 王赤清个人网站，并保留所有权利。
 * 网站地址: https://www.chiqinga.com
 * ----------------------------------------------------------------------------
 * 不允许对程序代码以任何形式任何目的的再发布。
 * 本程序采用thinkphp v5.0开发
 * ============================================================================
 * Author: chiqing_85
 * Time:17:32
 */

namespace app\admin\controller;

use think\Db;
use baksql\Baksql;

class Database extends Common
{
    private $bak;

    public function _initialize()
    {
        parent::_initialize();  // TODO: Change the autogenerated stub

        $this->bak = new Baksql(config('database'));
    }

    /**
     * 数据库列表
     * @return \think\response\View
     */
    public function index()
    {
        $datalist = Db()->query('show table STATUS');

       $this->assign('datalist', $datalist);

       return view();
    }

    /**
     * 备份数据库
     * @return int
     */
    public function backup()
    {
        $base = input('base/a');

        if(isset($base) && !empty($base))
        {
           $backup = $this->bak;

           $res = $backup->backup($base);

           return jsdata(200, $res, '');

        } else {

            return '请选中要备份的表……';
        }
    }

    /**
     *　数据表优化
     * @return int
     */

    public function optimize()
    {
        $base = input('base/a');

        if(isset($base) && !empty($base))
        {
            $base = implode('`,`', $base);

            $res = Db::query("OPTIMIZE TABLE `{$base}`");

            if($res)
            {
                return jsdata('200','数据表优化完成！');

            } else {

                return '优化失败，请重试！';
            }
        } else {

            return '请选中要优化的表……';
        }
    }

     /**
     * 数据表修复
     * @return int
     */
    public function repair()
    {
        $base = input('base/a');

        if(isset($base) && !empty($base))
        {
            $base = implode('`,`', $base);

            $res = Db::query("REPAIR TABLE `{$base}`");

            if($res)
            {
                return jsdata('200','数据表修复完成！');

            } else {

                return '数据表修复失败，请重试！';
            }
        } else {

            return '请选中要修复的表……';
        }
    }

    /**
     * 备份列表
     *  @return int
     */
    public function reduction ()
    {
        $reduction = $this->bak;

        $datalist =  $reduction->get_filelist();

        $this->assign('list', $datalist);

        return view();
    }

     /**
     * 下载
     * @return string
     */
    public function dowonload()
    {
        $base = input('base');

        $dowonload = $this->bak;

        $dowonload->downloadFile($base);

    }

    /**
     * 还愿数据库
     * @return int
     */
    public function restore()
    {
        $base = input('base');

        $restore = $this->bak;

        $res = $restore->restore($base);

        if($res)
        {
            return jsdata(200, $res, '');
        }
    }

     /**
     * 删除备份
     * @return string
     */

    public function delete()
    {
        $base = input('base');

        $delete = $this->bak;

        $res = $delete->delfilename($base);

        if($res)
        {
            return jsdata('200', $res,'');
        }
    }

    /**
     * 执行sql
     * @return \think\response\View
     */
    public function query()
    {
        if(input('__token__'))
        {
            $sql = input('query');
            if( !empty($sql)){

                $res = db()->execute($sql);

                if( $res) {

                    return jsdata(200, 'SQL执行成功!', '');

                } else{
                    return 'SQL执行失败!';
                }
            }else{

                return '提交数据不能为空!';
            }

        } else {

            return view();
        }
    }
}